name: Main workflow

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: false
          
      - name: Publish
        working-directory: src/Pruner
        run: dotnet publish -c Release -o publish
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: src/Pruner/publish/Pruner.Instrumenter.exe
