name: Main workflow

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: false
          
      - name: Publish
        working-directory: src
        run: dotnet publish -c Release -o publish

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          draft: false
          artifacts: "src/publish/Pruner.Instrumenter.exe"
